"""Add unique constraints to User model

Revision ID: 1ba225de586b
Revises: a4b3f138801c
Create Date: 2025-04-05 15:01:34.036482

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1ba225de586b'
down_revision: Union[str, None] = 'a4b3f138801c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_users_email', 'users', ['email'], schema='chrome_users')
    op.create_unique_constraint('uq_users_phone_number', 'users', ['phone_number'], schema='chrome_users')
    op.create_unique_constraint('uq_users_username', 'users', ['username'], schema='chrome_users')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_users_username', 'users', schema='chrome_users', type_='unique')
    op.drop_constraint('uq_users_phone_number', 'users', schema='chrome_users', type_='unique')
    op.drop_constraint('uq_users_email', 'users', schema='chrome_users', type_='unique')
    # ### end Alembic commands ###
