"""Updated the models

Revision ID: a4b3f138801c
Revises: 83e4621c3178
Create Date: 2025-04-05 10:24:34.944328

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a4b3f138801c'
down_revision: Union[str, None] = '83e4621c3178'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('actor_id', sa.Integer(), nullable=True),
    sa.Column('event_type', sa.String(length=50), nullable=False),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('target', sa.String(length=100), nullable=True),
    sa.Column('meta_info', sa.Text(), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=True),
    sa.ForeignKeyConstraint(['actor_id'], ['chrome_users.users.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['chrome_users.users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='chrome_users'
    )
    op.create_index(op.f('ix_chrome_users_audit_logs_id'), 'audit_logs', ['id'], unique=False, schema='chrome_users')
    op.create_table('user_job_queue',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('job_type', sa.String(length=100), nullable=True),
    sa.Column('payload', sa.Text(), nullable=True),
    sa.Column('scheduled_for', sa.TIMESTAMP(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('processed_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['chrome_users.users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='chrome_users'
    )
    op.create_index(op.f('ix_chrome_users_user_job_queue_id'), 'user_job_queue', ['id'], unique=False, schema='chrome_users')
    op.create_index(op.f('ix_chrome_users_user_job_queue_user_id'), 'user_job_queue', ['user_id'], unique=False, schema='chrome_users')
    op.drop_index('ix_chrome_users_user_audit_logs_id', table_name='user_audit_logs', schema='chrome_users')
    op.drop_table('user_audit_logs', schema='chrome_users')
    op.create_index(op.f('ix_chrome_users_captcha_challenges_session_id'), 'captcha_challenges', ['session_id'], unique=False, schema='chrome_users')
    op.alter_column('password_reset_tokens', 'token',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=255),
               existing_nullable=True,
               schema='chrome_users')
    op.drop_constraint('password_reset_tokens_token_key', 'password_reset_tokens', schema='chrome_users', type_='unique')
    op.create_index(op.f('ix_chrome_users_password_reset_tokens_token'), 'password_reset_tokens', ['token'], unique=True, schema='chrome_users')
    op.create_index(op.f('ix_chrome_users_password_reset_tokens_user_id'), 'password_reset_tokens', ['user_id'], unique=False, schema='chrome_users')
    op.drop_constraint('roles_name_key', 'roles', schema='chrome_users', type_='unique')
    op.create_index(op.f('ix_chrome_users_roles_name'), 'roles', ['name'], unique=True, schema='chrome_users')
    op.create_index(op.f('ix_chrome_users_user_logins_user_id'), 'user_logins', ['user_id'], unique=False, schema='chrome_users')
    op.create_index(op.f('ix_chrome_users_user_roles_role_id'), 'user_roles', ['role_id'], unique=False, schema='chrome_users')
    op.create_index(op.f('ix_chrome_users_user_roles_user_id'), 'user_roles', ['user_id'], unique=False, schema='chrome_users')
    op.add_column('user_sessions', sa.Column('token_hash', sa.String(length=255), nullable=True), schema='chrome_users')
    op.create_index(op.f('ix_chrome_users_user_sessions_user_id'), 'user_sessions', ['user_id'], unique=False, schema='chrome_users')
    op.create_unique_constraint(None, 'user_sessions', ['token_hash'], schema='chrome_users')
    op.add_column('users', sa.Column('phone_number', sa.String(length=20), nullable=True), schema='chrome_users')
    op.add_column('users', sa.Column('registration_ip', sa.String(length=45), nullable=True), schema='chrome_users')
    op.add_column('users', sa.Column('registration_user_agent', sa.String(length=255), nullable=True), schema='chrome_users')
    op.add_column('users', sa.Column('registered_via', sa.String(length=50), nullable=True), schema='chrome_users')
    op.add_column('users', sa.Column('registration_referrer', sa.String(length=255), nullable=True), schema='chrome_users')
    op.add_column('users', sa.Column('terms_accepted', sa.Boolean(), nullable=True), schema='chrome_users')
    op.add_column('users', sa.Column('terms_accepted_at', sa.TIMESTAMP(), nullable=True), schema='chrome_users')
    op.add_column('users', sa.Column('blocked_until', sa.TIMESTAMP(), nullable=True), schema='chrome_users')
    op.alter_column('users', 'profile_picture_url',
               existing_type=sa.TEXT(),
               type_=sa.String(length=255),
               existing_nullable=True,
               schema='chrome_users')
    op.drop_constraint('users_email_key', 'users', schema='chrome_users', type_='unique')
    op.drop_constraint('users_username_key', 'users', schema='chrome_users', type_='unique')
    op.create_index(op.f('ix_chrome_users_users_email'), 'users', ['email'], unique=True, schema='chrome_users')
    op.create_index(op.f('ix_chrome_users_users_username'), 'users', ['username'], unique=True, schema='chrome_users')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_chrome_users_users_username'), table_name='users', schema='chrome_users')
    op.drop_index(op.f('ix_chrome_users_users_email'), table_name='users', schema='chrome_users')
    op.create_unique_constraint('users_username_key', 'users', ['username'], schema='chrome_users')
    op.create_unique_constraint('users_email_key', 'users', ['email'], schema='chrome_users')
    op.alter_column('users', 'profile_picture_url',
               existing_type=sa.String(length=255),
               type_=sa.TEXT(),
               existing_nullable=True,
               schema='chrome_users')
    op.drop_column('users', 'blocked_until', schema='chrome_users')
    op.drop_column('users', 'terms_accepted_at', schema='chrome_users')
    op.drop_column('users', 'terms_accepted', schema='chrome_users')
    op.drop_column('users', 'registration_referrer', schema='chrome_users')
    op.drop_column('users', 'registered_via', schema='chrome_users')
    op.drop_column('users', 'registration_user_agent', schema='chrome_users')
    op.drop_column('users', 'registration_ip', schema='chrome_users')
    op.drop_column('users', 'phone_number', schema='chrome_users')
    op.drop_constraint(None, 'user_sessions', schema='chrome_users', type_='unique')
    op.drop_index(op.f('ix_chrome_users_user_sessions_user_id'), table_name='user_sessions', schema='chrome_users')
    op.drop_column('user_sessions', 'token_hash', schema='chrome_users')
    op.drop_index(op.f('ix_chrome_users_user_roles_user_id'), table_name='user_roles', schema='chrome_users')
    op.drop_index(op.f('ix_chrome_users_user_roles_role_id'), table_name='user_roles', schema='chrome_users')
    op.drop_index(op.f('ix_chrome_users_user_logins_user_id'), table_name='user_logins', schema='chrome_users')
    op.drop_index(op.f('ix_chrome_users_roles_name'), table_name='roles', schema='chrome_users')
    op.create_unique_constraint('roles_name_key', 'roles', ['name'], schema='chrome_users')
    op.drop_index(op.f('ix_chrome_users_password_reset_tokens_user_id'), table_name='password_reset_tokens', schema='chrome_users')
    op.drop_index(op.f('ix_chrome_users_password_reset_tokens_token'), table_name='password_reset_tokens', schema='chrome_users')
    op.create_unique_constraint('password_reset_tokens_token_key', 'password_reset_tokens', ['token'], schema='chrome_users')
    op.alter_column('password_reset_tokens', 'token',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=100),
               existing_nullable=True,
               schema='chrome_users')
    op.drop_index(op.f('ix_chrome_users_captcha_challenges_session_id'), table_name='captcha_challenges', schema='chrome_users')
    op.create_table('user_audit_logs',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('action', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('details', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('performed_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('ip_address', sa.VARCHAR(length=45), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['chrome_users.users.id'], name='user_audit_logs_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='user_audit_logs_pkey'),
    schema='chrome_users'
    )
    op.create_index('ix_chrome_users_user_audit_logs_id', 'user_audit_logs', ['id'], unique=False, schema='chrome_users')
    op.drop_index(op.f('ix_chrome_users_user_job_queue_user_id'), table_name='user_job_queue', schema='chrome_users')
    op.drop_index(op.f('ix_chrome_users_user_job_queue_id'), table_name='user_job_queue', schema='chrome_users')
    op.drop_table('user_job_queue', schema='chrome_users')
    op.drop_index(op.f('ix_chrome_users_audit_logs_id'), table_name='audit_logs', schema='chrome_users')
    op.drop_table('audit_logs', schema='chrome_users')
    # ### end Alembic commands ###
